# -*- coding: utf-8 -*-
"""HW1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bebrWn2dCFr387y3yNgF-KHpWpl46QFl
"""

!pip install openai PyPDF2 pandas tqdm

import os, pandas as pd
from tqdm import tqdm
from PyPDF2 import PdfReader
from openai import OpenAI

from google.colab import files
uploaded = files.upload()     # upload "state_of_ai.pdf"
pdf_path = list(uploaded.keys())[0]

reader = PdfReader(pdf_path)
text = ""
for page in reader.pages:
    text += page.extract_text() + "\n"

print("✅ Loaded", len(text.split()), "words from report")

context = " ".join(text.split()[:2571])
print(context[:800])   # preview

questions = [
    "What was NVIDIA's total revenue in Q3 FY25?",
    "Which segment contributed the most to revenue growth?",
    "How did the Data Center business perform compared to last year?",
    "What guidance did NVIDIA provide for Q4 FY25?",
    "What were the key drivers of NVIDIA's overall growth this quarter?"
]

from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI(api_key=api_key)

def make_prompts(question, context):
    return [
        f"Answer this question based only on the text below.\n\nText:\n{context}\n\nQuestion: {question}",
        f"You are a financial analyst. Using the report below, give a concise, data-backed answer.\n\n{context}\n\nQuestion: {question}",
        f"Summarize the answer in three bullet points, using only figures from the report.\n\n{context}\n\nQuestion: {question}",
        f"Quote relevant phrases from the report to justify your answer.\n\n{context}\n\nQuestion: {question}",
        f"If the question cannot be answered from the report, reply 'Not found in document.' Otherwise, give one-sentence answer.\n\n{context}\n\nQuestion: {question}"
    ]

results = []
for q in tqdm(questions):
    for i, prompt in enumerate(make_prompts(q, text), 1):  # Using full text
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3
        )
        answer = response.choices[0].message.content.strip()
        results.append({
            "Question": q,
            "Prompt_ID": i,
            "Response": answer
        })

df = pd.DataFrame(results)
print("✅ Completed all prompts. Showing sample:")
display(df.head())

df.to_csv("nvidia_cfo_prompt_experiments.csv", index=False)
from google.colab import files
files.download("nvidia_cfo_prompt_experiments.csv")